name: Go
on: [push]
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.12.x", "1.13.x", "1.14.x"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test project
        run: |
          go test -v -race ./...

      - name: Build project
        run: go build -v .
